### ISSUE TITLE
Memory consuming problem

### ISSUE THREAD

**Issue by mensurdurakovic** [luakit/luakit#300]
Hi! I made simple python script that is wrapper for Luakit, can enter and show some websites. Everything works fine, but after a while I noticed that Luakit is "eating" RAM memory more and more as long as it is open and showing some web site. At the end Luakit will crash and "eat" almost all available memory. 
Here is simple picture that is showing logs with memory and CPU usage

![logovi](https://cloud.githubusercontent.com/assets/5328533/15329119/cd5e0f00-1c57-11e6-9975-dff8af94e977.png)

Python script is running from my Raspberry Pi 3 (newest Raspbian update), approximate time for crashing depends what you are showing in Luakit, some websites like youtube eat more memory. In this picture I tested with youtube website, ran almost 6 hours before crashing.

My question is, why Luakit consumes RAM memory more and more as time goes on, and is there any way to fix this, except restarting Luakit ?

**Comment by mensurdurakovic** [comment]
Noticed that after executing rpi-update command luakit is displaying some strange console lines about cookies.db and other scripts that you can disable in rc.lua file (/etc/xdg/luakit/rc.lua), so I commented out those lines and now luakit does not eat RAM memory anymore.

**Comment by aidanholm** [comment]
It's possible that this issue is caused by Lua tables in the optional modules that are keyed by webviews without being weak-keyed, which would prevent garbage collection of webview objects. Just a guess though.

**Comment by mensurdurakovic** [comment]
Any idea how to manually run garbage collector ? Sometimes Luakit is

**Comment by aidanholm** [comment]
If that were the issue, and it may not be, then the only way of fixing it would be to fix the buggy modules. I'd suggest first calling `collectgarbage("count")` periodically from Lua and logging the return values (memory usage of Lua VM) while you browse for e.g. an hour or two, to narrow down the possible causes. If you see Lua VM memory usage climb then there's likely to be a leak; if it doesn't climb, the other likely culprit for increased overall consumption is WebKit.

**Comment by mensurdurakovic** [comment]
Thank you for advice, I will try!

**Comment by aidanholm** [comment]
Luakit has recently been updated to use WebKIt 2, and many old bugs have been fixed. Feel free to reopen if this issue reoccurs.

**Comment by Shados** [comment]
@aidanholm I'm pretty sure this is still an issue. I added some GC count logging to my userconf, and while it is consistently in the 16~28MB range, the RSS for the main luakit process does appear to leak over time.

As an extreme example, at one point I came back to my work laptop after a weekend to find it using 2.7GB, while the Lua VM was still only using 26MB. Usually the leak rate is slow enough to not matter too much -- I'm seeing 30MB-60MB increase in RSS over the course of a day, with the same set of tabs open at the start and end.

Of course, the webkit web processes also do strange things with memory usage, but that's not a luakit problem _per se_.

**Comment by hippi777** [comment]
hi there! :)

@Shados in case that u r using luajit then there was a recent conversaton about luajit on its mailing list or maybe github issues about mem leak that have been turned out that its about traces are keeping upvalues away from the gc, try jit.flush() and see if its like it was initially... in that case uve got the point, otherwise im clueless... ive seen previously my app that its continuously growing by a small amount of memory consumption, then ive tried jit.flush() and then memory consumption gone back to an initial range... maybe i will make upvalues locals however note that locals to be jit'ed have an upper limit around 100pcs if im right, but i dont know how to count them, like for a trace for a function for a scope for whatever... but anyhow i hope that will resolve my case, and anyways jit likes locals in general :) hint: some command line switches for lj can show its runtime jit stuffs and that can tell whenever there are too much locals and they are becoming a reason to abort a trace...

i hope my fast messy message could help anything, however feel free to ask if i wasnt clear, otoh this is the most i know around these stuffs :D

**Comment by Shados** [comment]
I am using luajit. I'll give that a try when I'm in at work tomorrow and let you know if it lowers the RSS back to roughly the initial level.

**Comment by Shados** [comment]
Nope, `jit.flush()` does not affect the RSS of the process. GC count is 18~20MB, RSS has grown to 660MB overnight. Restarting and reloading all the tabs brings the luakit process RSS down to ~80MB.

**Comment by hippi777** [comment]
ive got no idea then, i still havent switched to luakit, even if ive found it so much back in time (things are going slow for me as ive got a sh*tload of stuffs to do always) so i havent dug down in its sources...

**Comment by Shados** [comment]
Well, I've rebuilt luakit linked against lua 5.1 to see if it has the same problem as with luajit. I'll let you know tomorrow. GC count is still about the same (17~20MB).

**Comment by Shados** [comment]
Same issue does happen when built and linked against lua 5.1 instead of luajit; luakit process RSS steadily increases over time while GC count remains stable. I was wrong about GC count though, it's actually a bit higher in this configuration (20~36MB).
